### ISSUE TITLE
Dont work plugin

### ISSUE THREAD

**Issue by nevgin** [Vertamedia/clickhouse-grafana#181]
After filling in the plugin settings and clicking the Save and test button. An error - HTTP Error Internal Server Error.

Grafana 6.7.2 logs:
t=2020-04-23T17:09:54+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:199 (0x44d65b)\n/usr/local/go/src/runtime/signal_unix.go:394 (0x44d498)\n/root/project/pkg/api/pluginproxy/ds_proxy.go:215 (0xfcdced)\n/root/project/pkg/api/pluginproxy/ds_proxy.go:94 (0xfccc82)\n/root/project/pkg/api/dataproxy.go:36 (0x1449438)\n/usr/local/go/src/reflect/value.go:460 (0x4989d5)\n/usr/local/go/src/reflect/value.go:321 (0x498193)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975229)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x974bd9)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x9761c8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d9845)\n/root/project/pkg/middleware/request_tracing.go:25 (0x13d9838)\n/usr/local/go/src/reflect/value.go:460 (0x4989d5)\n/usr/local/go/src/reflect/value.go:321 (0x498193)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975229)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x974bd9)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x9761c8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d9019)\n/root/project/pkg/middleware/request_metrics.go:36 (0x13d9004)\n/usr/local/go/src/reflect/value.go:460 (0x4989d5)\n/usr/local/go/src/reflect/value.go:321 (0x498193)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975229)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x974bd9)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x9761c8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d8ecf)\n/root/project/pkg/middleware/recovery.go:160 (0x13d8ebd)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:79 (0x976070)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x974f39)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x974cc8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x9761c8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:112 (0x13d623b)\n/root/project/pkg/middleware/logger.go:34 (0x13d6226)\n/usr/local/go/src/reflect/value.go:460 (0x4989d5)\n/usr/local/go/src/reflect/value.go:321 (0x498193)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975229)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x974bd9)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/context.go:121 (0x9761c8)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/router.go:187 (0x987326)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/router.go:303 (0x981bf5)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.4/macaron.go:220 (0x97b0ba)\n/usr/local/go/src/net/http/server.go:2802 (0x707bc3)\n/usr/local/go/src/net/http/server.go:1890 (0x703564)\n/usr/local/go/src/runtime/asm_amd64.s:1357 (0x467db0)\n"
t=2020-04-23T17:09:54+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/ status=500 remote_addr=10.233.73.1 time_ms=2 size=122 referer=http://grafana.in.rlc.mts.ru/datasources/edit/2/

**Comment by Slach** [comment]
currently grafana-clickhouse it's an only frontend plugin

could you provide more information about your environment?
which version `clickhouse` do you use?
which version `clickhouse-grafana` plugin do you use?
which clickhouse-grafana plugin connection parameters do you use?

I tried to reproduce your error with latest master `git clone git@github.com/vertabedia/clickhouse-grafana.git` + `docker-compose` but  unsuccessful:

I used the following `docker-compose.yaml`
```
version: "3"
networks:
  grafana-clickhouse:
    
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    networks:
      grafana-clickhouse:
        aliases:
          - clickhouse
    ports:
    - 8123:8123
    - 9000:9000

  grafana:
    image: grafana/grafana:6.7.2
    networks:
      grafana-clickhouse:
        aliases:
          - grafana
    volumes:
    - ./:/var/lib/grafana/plugins/vertamedia-clickhouse/
    - ./grafana-clickhouse-datasource.yaml:/etc/grafana/provisioning/datasources/grafana-clickhouse-datasource.yaml
    ports:
    - 3000:3000
    depends_on:
      - clickhouse
```
docker-compose up -d grafana

and got datasource works fine
![image](https://user-images.githubusercontent.com/105560/81043649-12511e00-8ecc-11ea-8368-620834840c6c.png)
