### ISSUE TITLE
Cannot enable ClickHouse-Grafana plugin for Kuberenetes

### ISSUE THREAD

**Issue by miggi** [Vertamedia/clickhouse-grafana#251]
Hey guys, 

We really need your super-plugin for our Grafana inside Kuberenetes, but it seems to be not pulling by key "vertamedia-clickhouse-datasource" in helm chart. Do you have any ideas why ? 

See my config below: 

```
grafana:
  enabled: true
  namespaceOverride: ""
  plugins:
    - grafana-piechart-panel
    - btplc-status-dot-panel
    - digrich-bubblechart-panel
    - vertamedia-clickhouse-datasource
```

After applying I see other plugins, but NO  clickhouse-data source
