### ISSUE TITLE
Grafana 8.x.x alerts don't works with Provisioned data source

### ISSUE THREAD

**Issue by iceman2077** [Vertamedia/clickhouse-grafana#366]
Hi
I have Grafana 8.1.2 with plugin version 2.3.1.

The problem is that the alerts do not work, but the graphs work if the Provisioned data source is used, which we added to the helm values file of the grafana chart. 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/23246914/132674474-82b64878-760e-4613-bc4e-f989d1cae816.png">

At the same time, if you create a datasource via Grafana ui, then this error is absent and both alerts and graphs work.

Is there any way to fix this?
Thank you.

**Comment by Slach** [comment]
could you share your provisioned clickhouse datasource ini file without credentials?

**Comment by iceman2077** [comment]
```
apiVersion: 1
datasources:
- access: proxy
  isDefault: true
  name: VictoriaMetrics
  type: prometheus
  url: http://vm-victoria-metrics-cluster-vmselect:8481/select/0/prometheus
- access: proxy
  basicAuth: true
  basicAuthPassword: 1xm5NUtofZ4L4SFP
  basicAuthUser: svc_grafana
  isDefault: false
  name: ClickHouse
  type: vertamedia-clickhouse-datasource
  url: https://clickhouse.analytics.ecoinfra.io
- access: proxy
  basicAuth: true
  basicAuthPassword: xxx
  basicAuthUser: xxx
  isDefault: false
  name: ClickHouse-test
  type: vertamedia-clickhouse-datasource
  url: xxx
  ```

**Comment by iceman2077** [comment]
```
apiVersion: 1
datasources:
- access: proxy
  basicAuth: true
  basicAuthPassword: xxx
  basicAuthUser: xxx
  isDefault: false
  name: ClickHouse-test
  type: vertamedia-clickhouse-datasource
  url: xxx
  ```
