### ISSUE TITLE
Options for datasource configuration (yaml)

### ISSUE THREAD

**Issue by amarao** [Vertamedia/clickhouse-grafana#63]
New grafana allow administrators to use `conf/provisioning/datasources/something_here.yaml` mechanism to provide datasources through configuration  tools (e.g. ansible).

I'm trying to construct a valid json to describe a proper configuration, but it's hard. Could you add example into documentation somewhere?

My current best efforts:
```
apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    basicAuth: true
    url: http://78.140.148.41:8123
```
Things I don't know how to set up:

defaultDatabase:
User:
Password: (both for basicAuth mode).

Thanks!
